"""
Django settings for alliance_platform project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False)
)
# Read .env file
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-6ijxfdpz3-bdbm9b1qt2t0!xh)j90kiu6h*eje!!cgt*09u9ph')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'https://*.onrender.com',
    'https://*.vercel.app',
    'http://localhost:5173',
    'http://localhost:3000',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:3000',
])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',

    # Alliance One Platform
    'rest_framework',
    'kernel',
    'platform_services.identity',
    'platform_services.cloud',
    'platform_services.communication',
    'platform_services.dashboards',
    'platform_services.education.students',
    'platform_services.education.teachers',
    'platform_services.education.classes',
    'platform_services.education.subjects',
    'platform_services.education.grades',
    'platform_services.education.reports',
    'platform_services.education.finance',
    'platform_services.education.cards',
    'platform_services.education.core',
    'platform_services.inventory',
    'platform_services.library',
    'platform_services.finance',
    'platform_services.tasks',
    'platform_services.founder',
    'platform_services.alliance_ai',
    'platform_services.telegram',
    'platform_services.payments',
    'platform_services.alliance_modules',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'platform_services.identity.middleware.TenantMiddleware',
    'alliance_platform.middleware.ErrorTrackingMiddleware',
]

ROOT_URLCONF = 'alliance_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alliance_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db(default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}
DATABASES['default']['CONN_MAX_AGE'] = 600


# Caching
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Alliance ID Custom User Model
AUTH_USER_MODEL = 'identity.User'

# CORS
from corsheaders.defaults import default_headers

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = False
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-tenant-id',
    'x-user-email',
    'cache-control',
    'pragma',
    'expires',
    'dnt',
    'origin',
    'accept-encoding',
]
CORS_EXPOSE_HEADERS = ['*']

# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'platform_services.identity.authentication.AllianceTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

# Alliance AI LLM
GROQ_API_KEY = env('GROQ_API_KEY', default='')

# Celery Configuration
CELERY_BROKER_URL = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Telegram Bot Integration
TELEGRAM_BOT_TOKEN = env('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_WEBHOOK_SECRET = env('TELEGRAM_WEBHOOK_SECRET', default='alliance-one-telegram-secret-token-2026')
TELEGRAM_COMMUNITY_URL = env('TELEGRAM_COMMUNITY_URL', default='https://t.me/allianceonecommunity')
TELEGRAM_CHANNEL_URL = env('TELEGRAM_CHANNEL_URL', default='https://t.me/allianceonechannels')
TELEGRAM_CHANNEL_ID = env('TELEGRAM_CHANNEL_ID', default='@allianceonechannels')
TELEGRAM_COMMUNITY_ID = env('TELEGRAM_COMMUNITY_ID', default='@allianceonecommunity')

# Nelsius Payment Integration
NELSIUS_API_BASE_URL = env('NELSIUS_API_BASE_URL', default='http://localhost:8000/api/v1')
NELSIUS_SECRET_KEY = env('NELSIUS_SECRET_KEY', default='sk_test_dev_key')
