# Generated by Django 6.0.7 on 2026-08-16 02:23

import platform_services.identity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='active_modules',
            field=models.JSONField(default=platform_services.identity.models.default_modules, help_text='Liste des modules actifs pour cette organisation'),
        ),
    ]
