# Generated by Django 6.0.7 on 2026-09-15 14:51

import django.db.models.deletion
import platform_services.identity.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_organization_active_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('sub_sector', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='CM', help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('employee_count', models.CharField(blank=True, help_text='ex: 1-10, 11-50, 51-200', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('selected_modules', models.JSONField(default=platform_services.identity.models.default_selected_modules)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='identity.organization')),
            ],
        ),
    ]
