# Generated by Django 6.0.7 on 2026-10-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_organizationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User UI/UX preferences (theme, language, etc.)'),
        ),
    ]
