# Generated by Django 6.0.7 on 2026-09-22 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0003_organizationprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(help_text="Unique identifier (e.g. 'education', 'inventory')", unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('CORE', 'Core Platform'), ('OPERATIONS', 'Operations & Logistics'), ('FINANCE', 'Finance & Accounting'), ('PRODUCTIVITY', 'Productivity & CRM'), ('VERTICAL', 'Vertical (Education, Health)'), ('AI', 'Artificial Intelligence')], default='CORE', max_length=20)),
                ('accent_color', models.CharField(default='#4f46e5', max_length=20)),
                ('icon_name', models.CharField(default='Package', max_length=50)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('developer_name', models.CharField(default='Alliance Core Team', max_length=100)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_native', models.BooleanField(default=True, help_text='Built-in Alliance module')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BETA', 'Beta'), ('MAINTENANCE', 'Maintenance'), ('DEPRECATED', 'Deprecated')], default='ACTIVE', max_length=20)),
                ('permissions', models.JSONField(default=list, help_text='List of permissions required by this module')),
                ('features', models.JSONField(default=list, help_text='List of key features for display')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Installation'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended (Billing Issue)'), ('UNINSTALLED', 'Uninstalled')], default='PENDING', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Tenant-specific module configuration')),
                ('installed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='alliance_modules.module')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'verbose_name': 'Module Installation',
                'verbose_name_plural': 'Module Installations',
                'unique_together': {('organization', 'module')},
            },
        ),
        migrations.CreateModel(
            name='ModulePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="e.g. 'Starter', 'Professional'", max_length=100)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('is_free', models.BooleanField(default=False)),
                ('features', models.JSONField(default=list)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='alliance_modules.module')),
            ],
            options={
                'verbose_name': 'Module Plan',
                'verbose_name_plural': 'Module Plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('current_period_start', models.DateTimeField(auto_now_add=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='alliance_modules.moduleinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alliance_modules.moduleplan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
