# Generated by Django 6.0.7 on 2026-08-16 02:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_organization_active_modules'),
        ('inventory', '0004_productsupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tracking_serial',
            field=models.BooleanField(default=False, help_text='Exige le suivi par numéro de série unique'),
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('serial_number', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('IN_STOCK', 'En stock'), ('SOLD', 'Vendu / Sorti'), ('IN_TRANSIT', 'En transit'), ('LOST', 'Perdu / Rebut')], default='IN_STOCK', max_length=30)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='inventory.productbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='inventory.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Numéro de Série',
                'verbose_name_plural': 'Numéros de Série',
                'unique_together': {('organization', 'product', 'serial_number')},
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='serial_numbers',
            field=models.ManyToManyField(blank=True, related_name='movements', to='inventory.serialnumber'),
        ),
    ]
