# Generated by Django 6.0.7 on 2026-08-16 03:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_organization_active_modules'),
        ('inventory', '0005_product_tracking_serial_serialnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Nomenclature (BOM)',
                'verbose_name_plural': 'Nomenclatures (BOM)',
                'unique_together': {('organization', 'product', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.billofmaterial')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='inventory.product')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'verbose_name': 'Composant de Nomenclature',
                'verbose_name_plural': 'Composants de Nomenclature',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=60, unique=True)),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completed_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PLANNED', 'Planifié'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PLANNED', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.billofmaterial')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Ordre de Fabrication',
                'verbose_name_plural': 'Ordres de Fabrication',
                'ordering': ['-created_at'],
            },
        ),
    ]
