# Generated by Django 6.0.7 on 2026-09-22 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0003_organizationprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlliancePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('NELSIUS', 'Nelsius'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('MANUAL', 'Manual/Bank Transfer')], default='NELSIUS', max_length=50)),
                ('provider_transaction_code', models.CharField(blank=True, help_text='Transaction ID from the provider', max_length=255, null=True)),
                ('merchant_reference', models.CharField(help_text='Unique internal reference for idempotency (e.g. ALLIANCE-12345)', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Exact amount paid', max_digits=14)),
                ('currency', models.CharField(default='XAF', help_text='Currency ISO code', max_length=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=20)),
                ('payment_type', models.CharField(choices=[('CHECKOUT', 'Checkout (Hosted)'), ('DIRECT_PAY', 'Direct Pay (API)')], default='CHECKOUT', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional arbitrary data (e.g., checkout URLs, customer info)')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the transaction was successfully verified S2S', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alliance Payment',
                'verbose_name_plural': 'Alliance Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
