# Generated by Django 6.0.7 on 2026-09-16 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUpdateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_id', models.BigIntegerField(db_index=True, unique=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('command', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telegram Update Log',
                'verbose_name_plural': 'Telegram Update Logs',
                'ordering': ['-processed_at'],
            },
        ),
    ]
