# Generated by Django 6.0.7 on 2026-09-20 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegramidentity_telegramlinkcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('USER', 'Utilisateur'), ('ORG', 'Organisation'), ('CHANNEL', 'Canal Officiel'), ('COMMUNITY', 'Groupe Communautaire')], default='USER', max_length=20)),
                ('recipient_id', models.CharField(db_index=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(db_index=True, default='general', max_length=50)),
                ('level', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('ALERT', 'Alerte Critique')], default='INFO', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('DELIVERED', 'Délivré'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telegram Notification Log',
                'verbose_name_plural': 'Telegram Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_security', models.BooleanField(default=True, help_text='Alertes de sécurité et connexions')),
                ('alert_finance', models.BooleanField(default=True, help_text='Factures, paiements et relances')),
                ('alert_inventory', models.BooleanField(default=True, help_text='Ruptures de stock et alertes articles')),
                ('alert_education', models.BooleanField(default=True, help_text='Absences critiques et examens')),
                ('daily_digest', models.BooleanField(default=False, help_text="Résumé quotidien d'activité")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='telegram.telegramidentity')),
            ],
            options={
                'verbose_name': 'Telegram Notification Preference',
                'verbose_name_plural': 'Telegram Notification Preferences',
            },
        ),
    ]
