# Generated by Django 6.0.7 on 2026-08-16 04:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_finance', '0001_initial'),
        ('identity', '0002_organization_active_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TontineGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Nom du cercle (ex: Tontine des Cadres, Tontine Solidaire 2026)', max_length=200)),
                ('tontine_type', models.CharField(choices=[('ROTATIVE', 'Tontine Rotative (Chacun son tour / Rangs)'), ('ACCUMULATIVE', 'Tontine Épargne & Accumulation (Cagnotte de fin)'), ('SOLIDARITY', 'Fonds de Secours & Caisse de Solidarité')], default='ROTATIVE', max_length=20)),
                ('contribution_amount', models.DecimalField(decimal_places=2, help_text='Montant de la cotisation par part', max_digits=14)),
                ('currency', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar Américain ($)'), ('XOF', 'Franc CFA (F.CFA)'), ('GBP', 'Livre Sterling (£)'), ('CAD', 'Dollar Canadien ($ CA)'), ('CHF', 'Franc Suisse (CHF)')], default='XOF', max_length=10)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Hebdomadaire (Chaque semaine)'), ('BIWEEKLY', 'Bimensuelle (Toutes les 2 semaines)'), ('MONTHLY', 'Mensuelle (Chaque mois)'), ('QUARTERLY', 'Trimestrielle (Chaque trimestre)')], default='MONTHLY', max_length=20)),
                ('start_date', models.DateField(help_text='Date de démarrage du 1er tour')),
                ('end_date', models.DateField(blank=True, help_text='Date de fin estimée du cycle complet', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'En Préparation / Inscriptions'), ('ACTIVE', 'En Cours / Active'), ('COMPLETED', 'Terminée / Clôturée'), ('PAUSED', 'En Pause')], default='DRAFT', max_length=20)),
                ('late_penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pénalité forfaitaire en cas de retard de paiement', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, help_text="Règlement intérieur et conditions d'attribution", null=True)),
                ('account', models.ForeignKey(blank=True, help_text='Compte de trésorerie où transitent les fonds de la tontine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tontines', to='enterprise_finance.financialaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'verbose_name': 'Cercle de Tontine',
                'verbose_name_plural': 'Cercles de Tontine',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TontineMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(help_text='Nom complet du membre', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('shares_count', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Nombre de parts souscrites (ex: 1.0, 2.0, 0.5)', max_digits=5)),
                ('payout_order', models.IntegerField(default=1, help_text='Ordre de ramassage / Rang du tour où ce membre perçoit la cagnotte')),
                ('expected_payout_date', models.DateField(blank=True, null=True)),
                ('has_received_payout', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('COMPLETED', 'A Terminé / A Ramassé'), ('EXITED', 'Retiré')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='enterprise_finance.tontinegroup')),
            ],
            options={
                'verbose_name': 'Membre de Tontine',
                'verbose_name_plural': 'Membres de Tontine',
                'ordering': ['payout_order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='TontineRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('round_number', models.IntegerField(help_text='Numéro du tour (ex: 1, 2, 3...)')),
                ('due_date', models.DateField(help_text="Date d'échéance de versement des cotisations")),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant théorique total de la cagnotte', max_digits=14)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant réellement collecté auprès des membres', max_digits=14)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant net reversé au bénéficiaire', max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'À Venir / En Attente'), ('COLLECTING', 'Cotisations en cours'), ('COLLECTED', 'Cotisations Collectées'), ('PAID_OUT', 'Cagnotte Versée au Bénéficiaire'), ('CLOSED', 'Tour Clôturé')], default='PENDING', max_length=20)),
                ('payout_date', models.DateField(blank=True, help_text='Date effective du versement de la cagnotte', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(blank=True, help_text='Membre désigné pour remporter la cagnotte de ce tour', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary_rounds', to='enterprise_finance.tontinemember')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='enterprise_finance.tontinegroup')),
            ],
            options={
                'verbose_name': 'Tour de Tontine',
                'verbose_name_plural': 'Tours de Tontine',
                'ordering': ['round_number'],
                'unique_together': {('organization', 'tontine', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='TontinePayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Montant total brut de la cagnotte', max_digits=14)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retenues ou cotisations en avance déduites', max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Montant net remis au bénéficiaire', max_digits=14)),
                ('payout_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('TRANSFER', 'Virement Bancaire'), ('CARD', 'Carte Bancaire'), ('CASH', 'Espèces'), ('CHECK', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money'), ('DIRECT_DEBIT', 'Prélèvement Automatique'), ('ONLINE', 'Paiement en ligne'), ('OTHER', 'Autre')], default='TRANSFER', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='enterprise_finance.tontinemember')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='enterprise_finance.tontinegroup')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tontine_payouts', to='enterprise_finance.transaction')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='enterprise_finance.tontineround')),
            ],
            options={
                'verbose_name': 'Versement de Cagnotte',
                'verbose_name_plural': 'Versements de Cagnotte',
                'ordering': ['-payout_date'],
            },
        ),
        migrations.CreateModel(
            name='TontineContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('TRANSFER', 'Virement Bancaire'), ('CARD', 'Carte Bancaire'), ('CASH', 'Espèces'), ('CHECK', 'Chèque'), ('MOBILE_MONEY', 'Mobile Money'), ('DIRECT_DEBIT', 'Prélèvement Automatique'), ('ONLINE', 'Paiement en ligne'), ('OTHER', 'Autre')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PAID', 'Payée / Validée'), ('PENDING', 'En Attente'), ('LATE', 'En Retard')], default='PAID', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tontine_contributions', to='enterprise_finance.transaction')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='enterprise_finance.tontinegroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='enterprise_finance.tontinemember')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='enterprise_finance.tontineround')),
            ],
            options={
                'verbose_name': 'Cotisation de Tontine',
                'verbose_name_plural': 'Cotisations de Tontine',
                'ordering': ['-payment_date'],
                'unique_together': {('organization', 'round', 'member')},
            },
        ),
    ]
