# Generated by Django 6.0.7 on 2026-08-02 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('level', models.CharField(max_length=50)),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Groupe 1'), (2, 'Groupe 2'), (3, 'Groupe 3')], default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'unique_together': {('organization', 'name', 'level')},
            },
        ),
    ]
