# Generated by Django 6.0.7 on 2026-10-05 23:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0003_organizationprofile'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('service_id', models.IntegerField(help_text='ID du service IzyBoost')),
                ('service_name', models.CharField(max_length=255)),
                ('target_link', models.URLField(help_text='Lien du compte ou de la publication à booster', max_length=1000)),
                ('quantity', models.IntegerField()),
                ('comments', models.TextField(blank=True, help_text='Commentaires personnalisés si nécessaire', null=True)),
                ('remote_order_id', models.CharField(blank=True, help_text='ID de commande renvoyé par IzyBoost', max_length=100, null=True)),
                ('start_count', models.CharField(blank=True, max_length=50, null=True)),
                ('remains', models.CharField(blank=True, max_length=50, null=True)),
                ('cost_price_usd', models.DecimalField(decimal_places=4, help_text='Coût réel facturé par IzyBoost en USD', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Prix facturé au client final', max_digits=14)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente de paiement'), ('PROCESSING', 'En cours de traitement'), ('COMPLETED', 'Terminé'), ('PARTIAL', 'Partiellement terminé'), ('CANCELED', 'Annulé'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boost_orders', to='payments.alliancepayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
