# Generated by Django 6.0.7 on 2026-08-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ESP', 'Espèces'), ('MOMO', 'Mobile Money'), ('VIR', 'Virement Bancaire'), ('CHQ', 'Chèque')], default='ESP', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number_trans',
            field=models.CharField(blank=True, help_text='Numéro de chèque ou ID de transaction', max_length=100, null=True),
        ),
    ]
