# Generated by Django 6.0.7 on 2026-08-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='label',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('organization', 'label')},
        ),
    ]
