# Generated by Django 6.0.7 on 2026-08-04 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_academicyear_label_and_more'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('RENTREE', 'Rentrée'), ('VACANCES', 'Vacances'), ('FERIE', 'Jour férié'), ('EXAMEN', 'Examen'), ('EVALUATION', 'Évaluation'), ('CONSEIL', 'Conseil de classe'), ('REUNION_PROF', 'Réunion enseignants'), ('REUNION_PARENTS', 'Réunion parents'), ('CULTUREL', 'Journée culturelle'), ('SPORT', 'Journée sportive'), ('SORTIE', 'Sortie pédagogique'), ('FORMATION', 'Formation'), ('FERMETURE', 'Fermeture exceptionnelle'), ('CEREMONIE', 'Cérémonie'), ('SOUTENANCE', 'Soutenance'), ('CONCOURS', 'Concours'), ('ORIENTATION', 'Orientation'), ('INSCRIPTION', 'Inscription'), ('REINSCRIPTION', 'Réinscription'), ('REMISE_BULLETINS', 'Remise des bulletins')], default='CULTUREL', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('suspends_attendance', models.BooleanField(default=False)),
                ('locks_grades', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='classes.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'verbose_name': 'Événement académique',
                'verbose_name_plural': 'Événements académiques',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ('order', 'name'),
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='classes.level'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='classes.section'),
        ),
        migrations.DeleteModel(
            name='SchoolEvent',
        ),
    ]
