# Generated by Django 6.0.7 on 2026-08-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_schoolclass_capacity_academicevent_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frais de scolarité'),
        ),
    ]
