# Generated by Django 6.0.7 on 2026-08-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField()),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('user_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('payload', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'education_error_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
