# Generated by Django 6.0.7 on 2026-08-24 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionPlanModel',
            fields=[
                ('plan_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user_request', models.TextField()),
                ('organization_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('final_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alliance_ai_execution_plans',
            },
        ),
        migrations.CreateModel(
            name='ExecutionStepModel',
            fields=[
                ('step_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('tool_name', models.CharField(max_length=200)),
                ('arguments', models.JSONField()),
                ('dependencies', models.JSONField(default=list)),
                ('status', models.CharField(max_length=50)),
                ('output', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('verification_status', models.CharField(blank=True, max_length=255, null=True)),
                ('execution_metadata', models.JSONField(default=dict)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='alliance_ai.executionplanmodel')),
            ],
            options={
                'db_table': 'alliance_ai_execution_steps',
            },
        ),
    ]
