# Generated by Django 6.0.7 on 2026-08-02 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('old_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif de modification')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique de Note',
                'verbose_name_plural': 'Historiques de Notes',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.CharField(choices=[('seq1', 'Séquence 1'), ('seq2', 'Séquence 2'), ('seq3', 'Séquence 3'), ('seq4', 'Séquence 4'), ('seq5', 'Séquence 5'), ('seq6', 'Séquence 6')], max_length=10)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Validation de Séquence',
                'verbose_name_plural': 'Validations de Séquences',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.CharField(choices=[('seq1', 'Séquence 1'), ('seq2', 'Séquence 2'), ('seq3', 'Séquence 3'), ('seq4', 'Séquence 4'), ('seq5', 'Séquence 5'), ('seq6', 'Séquence 6')], max_length=10)),
                ('evaluation_type', models.CharField(choices=[('SEQ', 'Séquentielle'), ('EXAM', 'Examen'), ('TD', 'TD'), ('CC', 'CC')], default='SEQ', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='classes.academicyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
