# Generated by Django 6.0.7 on 2026-08-02 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('grades', '0003_initial'),
        ('identity', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='grades.grade'),
        ),
        migrations.AddField(
            model_name='gradehistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='sequencevalidation',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='classes.academicyear'),
        ),
        migrations.AddField(
            model_name='sequencevalidation',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sequencevalidation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization'),
        ),
        migrations.AddField(
            model_name='sequencevalidation',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='classes.schoolclass'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('organization', 'student', 'subject', 'sequence', 'academic_year', 'evaluation_type')},
        ),
        migrations.AlterUniqueTogether(
            name='sequencevalidation',
            unique_together={('organization', 'school_class', 'academic_year', 'sequence')},
        ),
    ]
