# Generated by Django 6.0.7 on 2026-08-02 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('matricule', models.CharField(blank=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('parent_name', models.CharField(max_length=150)),
                ('parent_phone', models.CharField(max_length=30)),
                ('parent_address', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='classes.schoolclass')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('is_absent', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('sequence', models.CharField(blank=True, max_length=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='classes.academicyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
            options={
                'verbose_name': 'Absence/Présence',
                'verbose_name_plural': 'Absences/Présences',
                'unique_together': {('organization', 'student', 'date', 'sequence')},
            },
        ),
    ]
