# Generated by Django 6.0.7 on 2026-08-04 11:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_schoolclass_capacity_academicevent_level_and_more'),
        ('identity', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school_class',
        ),
        migrations.AddField(
            model_name='student',
            name='lifecycle_status',
            field=models.CharField(choices=[('PRE_INSCRIT', 'Pré-inscrit'), ('ADMIS', 'Admis'), ('INSCRIT', 'Inscrit'), ('REINSCRIT', 'Réinscrit'), ('REDOUBLANT', 'Redoublant'), ('ABANDON', 'Abandon'), ('EXCLU', 'Exclu'), ('DIPLOME', 'Diplômé'), ('ALUMNI', 'Alumni')], default='PRE_INSCRIT', max_length=20),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_updated_at', models.DateTimeField(blank=True, help_text='Timestamp du client (Offline-First)', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('EN_COURS', 'En cours'), ('PROMU', 'Promu'), ('REDOUBLE', 'Redouble'), ('EXCLU', 'Exclu'), ('TRANSFERE', 'Transféré'), ('DIPLOME', 'Diplômé'), ('ABANDON', 'Abandon'), ('EN_ATTENTE', 'En attente')], default='EN_COURS', max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='classes.academicyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.organization')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='classes.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Inscription Annuelle',
                'verbose_name_plural': 'Inscriptions Annuelles',
                'ordering': ('-academic_year__start_year',),
                'unique_together': {('organization', 'student', 'academic_year')},
            },
        ),
    ]
