import uuid
from django.db import models
from django.conf import settings
from django.utils import timezone

class TelegramUpdateLog(models.Model):
    """
    Ensures idempotence for incoming Telegram updates.
    Telegram may re-deliver the exact same update_id during network retries.
    Logging every update_id guarantees single-execution semantics.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    update_id = models.BigIntegerField(unique=True, db_index=True)
    telegram_user_id = models.BigIntegerField(null=True, blank=True, db_index=True)
    command = models.CharField(max_length=100, blank=True)
    raw_payload = models.JSONField(default=dict, blank=True)
    processed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Telegram Update Log"
        verbose_name_plural = "Telegram Update Logs"
        ordering = ['-processed_at']

    def __str__(self):
        return f"Update {self.update_id} ({self.command or 'generic'}) at {self.processed_at}"


class TelegramIdentity(models.Model):
    """
    Represents a verified association between a Telegram account (telegram_user_id)
    and an authentic Alliance One User account.
    Stores the user's currently active Organization context.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='telegram_identities'
    )
    telegram_user_id = models.BigIntegerField(unique=True, db_index=True)
    telegram_chat_id = models.BigIntegerField(db_index=True)
    username = models.CharField(max_length=255, blank=True, default="")
    first_name = models.CharField(max_length=255, blank=True, default="")
    last_name = models.CharField(max_length=255, blank=True, default="")
    active_organization = models.ForeignKey(
        'identity.Organization',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='telegram_identities'
    )
    verified_at = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Telegram Identity"
        verbose_name_plural = "Telegram Identities"
        ordering = ['-created_at']

    def __str__(self):
        return f"Telegram {self.telegram_user_id} (@{self.username or 'anonymous'}) -> {self.user.email}"


class TelegramLinkCode(models.Model):
    """
    Ephemeral, single-use linking code generated by an authenticated Alliance One web user.
    Used to establish identity binding via deep linking or manual code entry.
    Default TTL: 10 minutes.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='telegram_link_codes'
    )
    code = models.CharField(max_length=64, unique=True, db_index=True)
    expires_at = models.DateTimeField()
    used_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Telegram Link Code"
        verbose_name_plural = "Telegram Link Codes"
        ordering = ['-created_at']

    @property
    def is_valid(self) -> bool:
        return self.used_at is None and self.expires_at > timezone.now()

    def __str__(self):
        status = "USED" if self.used_at else ("EXPIRED" if self.expires_at <= timezone.now() else "VALID")
        return f"LinkCode {self.code} ({status}) for {self.user.email}"
